version: '3.3'

services:
    nginx:

        build: ./nginx

        container_name: nginx

        ports:
            - "80:80"
            - "443:443"

        volumes:
            - ./nginx/config:/etc/nginx/conf.d
            - ./nginx/www:/var/www/
            - ./nginx/logs:/var/log/nginx/

        links:
            - php

    php:

        build: ./php-fpm

        container_name: php-fpm

        volumes:
            - ./nginx/www:/var/www

        links:
            - mysql

    mysql:

        build: ./mariadb

        container_name: mysql

        environment:
            - MYSQL_ROOT_PASSWORD=toor
            - MYSQL_DATABASE=db
            - MYSQL_USER=db
            - MYSQL_PASSWORD=db

        volumes:
            - ./mariadb/db:/var/lib/mysql
